# Box-3 Utilities Display (ESPHome Package)
# Version: 0.2.9
#
# Changes from 0.2.8:
# - Fixed top-row alignment so Indoor and Outdoor blocks are symmetric
#   * Outdoor label and temperature now right-aligned to the same margin
#     that Indoor uses on the left.
# - No logic or font changes; spacing only.

substitutions:
  thermostat_entity: climate.ecobee_thermostat

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

interval:
  - interval: 30s
    then:
      - script.execute: request_draw

sensor:
  - platform: homeassistant
    id: avg_indoor_temp
    entity_id: sensor.average_indoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.outdoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_power_w
    entity_id: sensor.house_electric_meter_power_minute_average
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_energy_month
    entity_id: sensor.house_electric_meter_energy_this_month
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: gas_now_flow
    lambda: |-
      return 0.0;
    update_interval: 5s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: gas_month_ccf
    lambda: |-
      return 12.3;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: water_now_flow
    lambda: |-
      return 0.0;
    update_interval: 5s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: water_month_gal
    lambda: |-
      return 824;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

text_sensor:
  - platform: homeassistant
    id: hvac_action
    entity_id: ${thermostat_entity}
    attribute: hvac_action
    internal: true
    on_value:
      - script.execute: request_draw

font:
  - file:
      type: gfonts
      family: Figtree
      weight: 600
    id: font_title
    size: 18

  - file:
      type: gfonts
      family: Figtree
      weight: 500
    id: font_label
    size: 14

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_value
    size: 20

  - file: https://unpkg.com/@mdi/font@7.4.47/fonts/materialdesignicons-webfont.ttf
    id: font_mdi
    size: 22
    glyphs:
      - "󰈸"          # mdi:fire (F0238)
      - "󰜗"          # mdi:snowflake (F0717)
      - "\U000F140C" # Electric (F140C)
      - "\U000F0E0A" # Water (F0E0A)

display:
  - platform: ili9xxx
    model: S3BOX
    id: box_display
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    invert_colors: false
    update_interval: never
    lambda: |-
      const Color paper = Color(255,255,255);
      const Color ink   = Color(0,0,0);

      it.fill(paper);

      auto fill_round = [&](int x, int y, int w, int h, int r, Color c) {
        it.filled_rectangle(x+r, y, w-2*r, h, c);
        it.filled_rectangle(x, y+r, r, h-2*r, c);
        it.filled_rectangle(x+w-r, y+r, r, h-2*r, c);
        it.filled_circle(x+r, y+r, r, c);
        it.filled_circle(x+w-r-1, y+r, r, c);
        it.filled_circle(x+r, y+h-r-1, r, c);
        it.filled_circle(x+w-r-1, y+h-r-1, r, c);
      };

      auto tile = [&](int x, int y, int w, int h, int r) {
        fill_round(x, y, w, h, r, ink);
        fill_round(x+1, y+1, w-2, h-2, r-1, paper);
      };

      // ----------------
      // Top strip (symmetric layout)
      // ----------------
      const int LEFT_X  = 10;
      const int RIGHT_X = 310;

      it.print(LEFT_X, 8, id(font_label), ink, "Indoor");
      it.printf(LEFT_X + 52, 6, id(font_value), ink, "%.0f°", id(avg_indoor_temp).state);

      it.print(RIGHT_X, 8, id(font_label), ink, TextAlign::TOP_RIGHT, "Outdoor");
      it.printf(RIGHT_X, 6, id(font_value), ink, TextAlign::TOP_RIGHT, "%.0f°", id(outdoor_temp).state);

      const std::string act = id(hvac_action).state;
      if (act == "heating") {
        it.print(152, 6, id(font_mdi), ink, "󰈸");
      } else if (act == "cooling") {
        it.print(152, 6, id(font_mdi), ink, "󰜗");
      }

      it.line(10, 34, 310, 34, ink);

      // ----------------
      // Utility cards
      // ----------------
      int y = 44;
      const int h = 56;

      tile(10, y, 300, h, 14);
      it.print(22, y+14, id(font_mdi), ink, "\U000F140C");
      it.print(44, y+10, id(font_title), ink, "Electricity");
      it.printf(44, y+34, id(font_label), ink, "Now %.0f W", id(electric_power_w).state);
      it.printf(170, y+34, id(font_label), ink, "Month %.1f kWh", id(electric_energy_month).state);

      y += h + 10;
      tile(10, y, 300, h, 14);
      it.print(22, y+14, id(font_mdi), ink, "󰈸");
      it.print(44, y+10, id(font_title), ink, "Gas");
      it.printf(44, y+34, id(font_label), ink, "Now %.2f", id(gas_now_flow).state);
      it.printf(170, y+34, id(font_label), ink, "Month %.1f CCF", id(gas_month_ccf).state);

      y += h + 10;
      tile(10, y, 300, h, 14);
      it.print(22, y+14, id(font_mdi), ink, "\U000F0E0A");
      it.print(44, y+10, id(font_title), ink, "Water");
      it.printf(44, y+34, id(font_label), ink, "Now %.1f", id(water_now_flow).state);
      it.printf(170, y+34, id(font_label), ink, "Month %.0f gal", id(water_month_gal).state);

script:
  - id: request_draw
    mode: restart
    then:
      - component.update: box_display
