# Box-3 Utilities Display (ESPHome Package)
# Version: 0.2.1
#
# PURE PACKAGE FILE (safe for `packages:` inclusion)

substitutions:
  thermostat_entity: climate.ecobee_thermostat

# Required for ili9xxx
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

# Safety refresh (plus on_value triggers)
interval:
  - interval: 30s
    then:
      - script.execute: request_draw

sensor:
  # HVAC temps
  - platform: homeassistant
    id: avg_indoor_temp
    entity_id: sensor.average_indoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.outdoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  # Electric (Emporia)
  - platform: homeassistant
    id: electric_power_w
    entity_id: sensor.house_electric_meter_power_minute_average
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_energy_month
    entity_id: sensor.house_electric_meter_energy_this_month
    internal: true
    on_value:
      - script.execute: request_draw

  # Gas placeholders (swap later)
  - platform: template
    id: gas_now_flow
    lambda: |-
      static int t = 0;
      t++;
      if ((t % 25) < 3) return 0.12f;
      return 0.00f;
    update_interval: 3s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: gas_month_ccf
    lambda: |-
      static float v = 12.3;
      v += 0.01;
      return v;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

  # Water placeholders
  - platform: template
    id: water_now_flow
    lambda: |-
      static int t = 0;
      t++;
      if ((t % 35) < 4) return 0.7f;
      return 0.0f;
    update_interval: 3s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: water_month_gal
    lambda: |-
      static float v = 820;
      v += 1;
      return v;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

text_sensor:
  # HVAC action from climate attribute (heating/cooling/idle)
  - platform: homeassistant
    id: hvac_action
    entity_id: ${thermostat_entity}
    attribute: hvac_action
    internal: true
    on_value:
      - script.execute: request_draw

font:
  - file:
      type: gfonts
      family: Figtree
      weight: 600
    id: font_top_label
    size: 16

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_top_value
    size: 18

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_tile_title
    size: 18

  - file:
      type: gfonts
      family: Figtree
      weight: 500
    id: font_tile_label
    size: 14

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_tile_value
    size: 18

  # MDI font (same approach as your original file — explicit glyphs)
  - file: https://unpkg.com/@mdi/font@7.3.67/fonts/materialdesignicons-webfont.ttf
    id: font_mdi
    size: 24
    glyphs:
      - "\U000F0238"  # mdi:fire
      - "\U000F0717"  # mdi:snowflake
      - "\U000F140B"  # mdi:lightning-bolt
      - "\U000F0647"  # mdi:gas-cylinder
      - "\U000F058C"  # mdi:water

display:
  - platform: ili9xxx
    model: S3BOX
    id: box_display
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    invert_colors: false
    update_interval: never
    lambda: |-
      // Paper / ink palette
      const Color paper  = Color(0xF3, 0xF1, 0xE7);
      const Color ink    = Color(0x11, 0x11, 0x11);
      const Color muted  = Color(0x55, 0x55, 0x55);
      const Color border = Color(0xAA, 0xA7, 0x9E);
      const Color white  = Color(0xFF, 0xFF, 0xFF);

      const Color hvac_heat = Color(255, 0, 0);
      const Color hvac_cool = Color(0, 140, 255);

      it.fill(paper);

      // ---- Helpers: rounded rect (filled + outline) ----
      auto fill_round = [&](int x, int y, int w, int h, int r, Color c) {
        it.filled_rectangle(x + r, y, w - 2*r, h, c);
        it.filled_rectangle(x, y + r, r, h - 2*r, c);
        it.filled_rectangle(x + w - r, y + r, r, h - 2*r, c);
        it.filled_circle(x + r,          y + r,          r, c);
        it.filled_circle(x + w - r - 1,  y + r,          r, c);
        it.filled_circle(x + r,          y + h - r - 1,  r, c);
        it.filled_circle(x + w - r - 1,  y + h - r - 1,  r, c);
      };

      auto stroke_round = [&](int x, int y, int w, int h, int r, Color c) {
        it.line(x + r, y, x + w - r - 1, y, c);
        it.line(x + r, y + h - 1, x + w - r - 1, y + h - 1, c);
        it.line(x, y + r, x, y + h - r - 1, c);
        it.line(x + w - 1, y + r, x + w - 1, y + h - r - 1, c);
        it.circle(x + r,         y + r,         r, c);
        it.circle(x + w - r - 1, y + r,         r, c);
        it.circle(x + r,         y + h - r - 1, r, c);
        it.circle(x + w - r - 1, y + h - r - 1, r, c);
      };

      // ---- Top strip (compact) ----
      // Indoor (left)
      it.print(10, 8, id(font_top_label), muted, "Indoor");
      if (!isnan(id(avg_indoor_temp).state)) {
        it.printf(70, 8, id(font_top_value), ink, "%.1f°", id(avg_indoor_temp).state);
      } else {
        it.print(70, 8, id(font_top_value), ink, "--");
      }

      // Outdoor (right)
      it.print(210, 8, id(font_top_label), muted, "Outdoor");
      if (!isnan(id(outdoor_temp).state)) {
        it.printf(282, 8, id(font_top_value), ink, "%.1f°", id(outdoor_temp).state);
      } else {
        it.print(282, 8, id(font_top_value), ink, "--");
      }

      // HVAC icon (center) — ONLY when heating/cooling
      if (id(hvac_action).has_state()) {
        const std::string action = id(hvac_action).state.c_str();
        if (action == "heating") {
          it.print(160, 8, id(font_mdi), hvac_heat, TextAlign::TOP_CENTER, "\U000F0238");
        } else if (action == "cooling") {
          it.print(160, 8, id(font_mdi), hvac_cool, TextAlign::TOP_CENTER, "\U000F0717");
        }
      }

      it.line(10, 38, 310, 38, border);

      // ---- Pill tiles ----
      const int tx = 10;
      const int tw = 300;
      const int th = 56;
      const int tr = 14;
      const int gap = 10;

      int y = 48;

      auto fmt_w_or_kw = [&](float w, char* out, size_t n) {
        if (isnan(w)) { snprintf(out, n, "--"); return; }
        if (w < 1000.0f) snprintf(out, n, "%.0f W", w);
        else snprintf(out, n, "%.2f kW", w / 1000.0f);
      };

      auto draw_tile = [&](int y, const char* title, const char* icon_glyph,
                           const char* now_value, const char* month_value) {
        fill_round(tx, y, tw, th, tr, white);
        stroke_round(tx, y, tw, th, tr, border);

        // icon + title
        it.print(tx + 14, y + 14, id(font_mdi), ink, icon_glyph);
        it.print(tx + 48, y + 10, id(font_tile_title), ink, title);

        // now / month
        it.print(tx + 48, y + 32, id(font_tile_label), muted, "Now");
        it.print(tx + 90, y + 30, id(font_tile_value), ink, now_value);

        it.print(tx + 176, y + 32, id(font_tile_label), muted, "Month");
        it.print(tx + 232, y + 30, id(font_tile_value), ink, month_value);
      };

      // Electricity
      char e_now[24];
      fmt_w_or_kw(id(electric_power_w).state, e_now, sizeof(e_now));

      char e_month[24];
      if (!isnan(id(electric_energy_month).state)) snprintf(e_month, sizeof(e_month), "%.1f kWh", id(electric_energy_month).state);
      else snprintf(e_month, sizeof(e_month), "-- kWh");

      draw_tile(y, "Electricity", "\U000F140B", e_now, e_month);

      // Gas
      y += th + gap;
      char g_now[24];
      snprintf(g_now, sizeof(g_now), "%.2f", id(gas_now_flow).state);

      char g_month[24];
      snprintf(g_month, sizeof(g_month), "%.1f CCF", id(gas_month_ccf).state);

      draw_tile(y, "Gas", "\U000F0647", g_now, g_month);

      // Water
      y += th + gap;
      char w_now[24];
      snprintf(w_now, sizeof(w_now), "%.1f", id(water_now_flow).state);

      char w_month[24];
      snprintf(w_month, sizeof(w_month), "%.0f gal", id(water_month_gal).state);

      draw_tile(y, "Water", "\U000F058C", w_now, w_month);

script:
  - id: request_draw
    mode: restart
    then:
      - component.update: box_display
