# Box-3 Utilities Display (ESPHome Package)
# Version: 0.2.2
#
# PURE PACKAGE FILE (safe for `packages:` inclusion)
#
# Tweaks vs 0.2.1:
# - Indoor/Outdoor temps rounded to whole numbers
# - True white background + true white tiles (no gray fill)
# - Removed corner circles by using a 2-layer rounded-rect border technique
# - Moved utility values left so everything sits comfortably inside each pill

substitutions:
  thermostat_entity: climate.ecobee_thermostat

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

interval:
  - interval: 30s
    then:
      - script.execute: request_draw

sensor:
  - platform: homeassistant
    id: avg_indoor_temp
    entity_id: sensor.average_indoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.outdoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_power_w
    entity_id: sensor.house_electric_meter_power_minute_average
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_energy_month
    entity_id: sensor.house_electric_meter_energy_this_month
    internal: true
    on_value:
      - script.execute: request_draw

  # Placeholders (swap later)
  - platform: template
    id: gas_now_flow
    lambda: |-
      static int t = 0;
      t++;
      if ((t % 25) < 3) return 0.12f;
      return 0.00f;
    update_interval: 3s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: gas_month_ccf
    lambda: |-
      static float v = 12.3;
      v += 0.01;
      return v;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: water_now_flow
    lambda: |-
      static int t = 0;
      t++;
      if ((t % 35) < 4) return 0.7f;
      return 0.0f;
    update_interval: 3s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: water_month_gal
    lambda: |-
      static float v = 820;
      v += 1;
      return v;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

text_sensor:
  - platform: homeassistant
    id: hvac_action
    entity_id: ${thermostat_entity}
    attribute: hvac_action
    internal: true
    on_value:
      - script.execute: request_draw

# Fonts
font:
  - file:
      type: gfonts
      family: Figtree
      weight: 600
    id: font_title
    size: 18

  - file:
      type: gfonts
      family: Figtree
      weight: 500
    id: font_label
    size: 14

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_value
    size: 20

  # MDI (must match what worked in your original YAML)
  - file:
      type: gfonts
      family: Material Design Icons
      weight: 400
    id: font_mdi
    size: 22

display:
  - platform: ili9xxx
    model: S3BOX
    id: box_display
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    invert_colors: false
    update_interval: never
    lambda: |-
      // Pure black/white e-ink vibe
      const Color paper = Color(0xFF, 0xFF, 0xFF);
      const Color ink   = Color(0x00, 0x00, 0x00);

      it.fill(paper);

      // Rounded rect fill helper
      auto fill_round = [&](int x, int y, int w, int h, int r, Color c) {
        it.filled_rectangle(x + r, y, w - 2*r, h, c);
        it.filled_rectangle(x, y + r, r, h - 2*r, c);
        it.filled_rectangle(x + w - r, y + r, r, h - 2*r, c);
        it.filled_circle(x + r,           y + r,           r, c);
        it.filled_circle(x + w - r - 1,   y + r,           r, c);
        it.filled_circle(x + r,           y + h - r - 1,   r, c);
        it.filled_circle(x + w - r - 1,   y + h - r - 1,   r, c);
      };

      // Tile helper: draw border as an outer rounded rect (ink) + inner rounded rect (paper)
      auto tile = [&](int x, int y, int w, int h, int r) {
        fill_round(x, y, w, h, r, ink);                 // border layer
        fill_round(x+1, y+1, w-2, h-2, r-1, paper);     // inner fill layer
      };

      // ---- Top strip: Indoor / (center HVAC icon) / Outdoor ----
      it.print(10, 8, id(font_label), ink, "Indoor");
      if (!isnan(id(avg_indoor_temp).state)) it.printf(62, 6, id(font_value), ink, "%.0f°", id(avg_indoor_temp).state);
      else it.print(62, 6, id(font_value), ink, "--");

      it.print(228, 8, id(font_label), ink, "Outdoor");
      if (!isnan(id(outdoor_temp).state)) it.printf(290, 6, id(font_value), ink, "%.0f°", id(outdoor_temp).state);
      else it.print(290, 6, id(font_value), ink, "--");

      // HVAC icon centered: only show when heating/cooling; idle = blank
      // (Uses the same "words" from your existing hvac_action attribute: "heating", "cooling", etc.)
      const std::string act = id(hvac_action).state;
      if (act == "heating") {
        // Fire icon (codepoint from your working config)
        it.print(154, 6, id(font_mdi), ink, "\U000F0238"); // mdi-fire
      } else if (act == "cooling") {
        it.print(154, 6, id(font_mdi), ink, "\U000F0717"); // mdi-snowflake
      }

      // divider
      it.line(10, 34, 310, 34, ink);

      // ---- Pill tiles ----
      const int tx = 10;
      const int tw = 300;
      const int th = 56;
      const int tr = 14;
      const int gap = 10;
      int y = 44;

      auto fmt_w_or_kw = [&](float w, char* out, size_t n) {
        if (isnan(w)) { snprintf(out, n, "--"); return; }
        if (w < 1000.0f) snprintf(out, n, "%.0f W", w);
        else snprintf(out, n, "%.2f kW", w / 1000.0f);
      };

      auto draw_tile = [&](int x, int y, const char* icon, const char* title,
                           const char* now_value,
                           const char* month_value) {
        tile(x, y, tw, th, tr);

        // icon + title row
        it.print(x + 14, y + 12, id(font_mdi), ink, icon);
        it.print(x + 44, y + 10, id(font_title), ink, title);

        // bottom row: "Now <value>" and "Month <value>" (values moved left)
        it.print(x + 44,  y + 34, id(font_label), ink, "Now");
        it.print(x + 84,  y + 34, id(font_label), ink, now_value);

        it.print(x + 158, y + 34, id(font_label), ink, "Month");
        it.print(x + 210, y + 34, id(font_label), ink, month_value);
      };

      // Electricity values
      char e_now[24];
      fmt_w_or_kw(id(electric_power_w).state, e_now, sizeof(e_now));

      char e_month[24];
      if (!isnan(id(electric_energy_month).state)) snprintf(e_month, sizeof(e_month), "%.1f kWh", id(electric_energy_month).state);
      else snprintf(e_month, sizeof(e_month), "-- kWh");

      draw_tile(tx, y,
        "\U000F140B",  // mdi-lightning-bolt
        "Electricity",
        e_now,
        e_month
      );

      // Gas
      y += th + gap;
      char g_now[24];
      snprintf(g_now, sizeof(g_now), "%.2f", id(gas_now_flow).state);

      char g_month[24];
      snprintf(g_month, sizeof(g_month), "%.1f CCF", id(gas_month_ccf).state);

      draw_tile(tx, y,
        "\U000F0647",  // mdi-gas-cylinder
        "Gas",
        g_now,
        g_month
      );

      // Water
      y += th + gap;
      char w_now[24];
      snprintf(w_now, sizeof(w_now), "%.1f", id(water_now_flow).state);

      char w_month[24];
      snprintf(w_month, sizeof(w_month), "%.0f gal", id(water_month_gal).state);

      draw_tile(tx, y,
        "\U000F058C",  // mdi-water
        "Water",
        w_now,
        w_month
      );

script:
  - id: request_draw
    mode: restart
    then:
      - component.update: box_display
