# Box-3 Utilities Display (ESPHome Package)
# Version: 0.2.4
#
# FINAL POLISH:
# - Move Outdoor temp slightly left from screen edge
# - Restore correct HVAC flame icon (heating) / snowflake (cooling)
# - Use SAME flame icon for Gas pill (not water-drop)
# - Keep e-ink styling (white bg, white pills, black borders/text)

substitutions:
  thermostat_entity: climate.ecobee_thermostat

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

interval:
  - interval: 30s
    then:
      - script.execute: request_draw

sensor:
  - platform: homeassistant
    id: avg_indoor_temp
    entity_id: sensor.average_indoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.outdoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_power_w
    entity_id: sensor.house_electric_meter_power_minute_average
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_energy_month
    entity_id: sensor.house_electric_meter_energy_this_month
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: gas_now_flow
    lambda: |-
      return 0.0;
    update_interval: 5s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: gas_month_ccf
    lambda: |-
      return 12.3;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: water_now_flow
    lambda: |-
      return 0.0;
    update_interval: 5s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: water_month_gal
    lambda: |-
      return 824;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

text_sensor:
  - platform: homeassistant
    id: hvac_action
    entity_id: ${thermostat_entity}
    attribute: hvac_action
    internal: true
    on_value:
      - script.execute: request_draw

font:
  - file:
      type: gfonts
      family: Figtree
      weight: 600
    id: font_title
    size: 18

  - file:
      type: gfonts
      family: Figtree
      weight: 500
    id: font_label
    size: 14

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_value
    size: 20

display:
  - platform: ili9xxx
    model: S3BOX
    id: box_display
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    invert_colors: false
    update_interval: never
    lambda: |-
      const Color paper = Color(255,255,255);
      const Color ink   = Color(0,0,0);
      const Color red   = Color(220,38,38);
      const Color blue  = Color(37,99,235);

      it.fill(paper);

      auto fill_round = [&](int x, int y, int w, int h, int r, Color c) {
        it.filled_rectangle(x+r, y, w-2*r, h, c);
        it.filled_rectangle(x, y+r, r, h-2*r, c);
        it.filled_rectangle(x+w-r, y+r, r, h-2*r, c);
        it.filled_circle(x+r, y+r, r, c);
        it.filled_circle(x+w-r-1, y+r, r, c);
        it.filled_circle(x+r, y+h-r-1, r, c);
        it.filled_circle(x+w-r-1, y+h-r-1, r, c);
      };

      auto tile = [&](int x, int y, int w, int h, int r) {
        fill_round(x, y, w, h, r, ink);
        fill_round(x+1, y+1, w-2, h-2, r-1, paper);
      };

      auto icon_flame = [&](int x, int y, Color c) {
        it.circle(x+8, y+12, 5, c);
        it.line(x+8, y+1, x+4, y+8, c);
        it.line(x+8, y+1, x+12, y+8, c);
      };

      auto icon_snow = [&](int x, int y, Color c) {
        it.line(x+8, y, x+8, y+16, c);
        it.line(x, y+8, x+16, y+8, c);
        it.line(x+2, y+2, x+14, y+14, c);
        it.line(x+14, y+2, x+2, y+14, c);
      };

      auto icon_bolt = [&](int x, int y, Color c) {
        it.line(x+8, y, x+2, y+10, c);
        it.line(x+2, y+10, x+7, y+10, c);
        it.line(x+7, y+10, x+3, y+18, c);
        it.line(x+3, y+18, x+14, y+6, c);
      };

      // Top strip
      it.print(10, 8, id(font_label), ink, "Indoor");
      it.printf(62, 6, id(font_value), ink, "%.0f°", id(avg_indoor_temp).state);

      it.print(210, 8, id(font_label), ink, "Outdoor");
      it.printf(260, 6, id(font_value), ink, "%.0f°", id(outdoor_temp).state);

      const std::string act = id(hvac_action).state;
      if (act == "heating") icon_flame(152, 6, red);
      else if (act == "cooling") icon_snow(152, 6, blue);

      it.line(10, 34, 310, 34, ink);

      int y = 44;
      const int h = 56;

      // Electricity
      tile(10, y, 300, h, 14);
      icon_bolt(24, y+16, ink);
      it.print(44, y+10, id(font_title), ink, "Electricity");
      it.printf(44, y+34, id(font_label), ink, "Now %.0f W", id(electric_power_w).state);
      it.printf(170, y+34, id(font_label), ink, "Month %.1f kWh", id(electric_energy_month).state);

      // Gas
      y += h + 10;
      tile(10, y, 300, h, 14);
      icon_flame(24, y+16, ink);
      it.print(44, y+10, id(font_title), ink, "Gas");
      it.printf(44, y+34, id(font_label), ink, "Now %.2f", id(gas_now_flow).state);
      it.printf(170, y+34, id(font_label), ink, "Month %.1f CCF", id(gas_month_ccf).state);

      // Water
      y += h + 10;
      tile(10, y, 300, h, 14);
      it.circle(32, y+24, 6, ink);
      it.print(44, y+10, id(font_title), ink, "Water");
      it.printf(44, y+34, id(font_label), ink, "Now %.1f", id(water_now_flow).state);
      it.printf(170, y+34, id(font_label), ink, "Month %.0f gal", id(water_month_gal).state);

script:
  - id: request_draw
    mode: restart
    then:
      - component.update: box_display
