# Version: 0.3.0-pre1-touch-debug

substitutions:
  thermostat_entity: climate.ecobee_thermostat

esphome:
  name: box-3-utilities
  friendly_name: Box 3 Utilities
  on_boot:
    priority: 600
    then:
      - display.page.show: home_page
      - component.update: box_display

esp32:
  board: esp32s3box
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

i2c:
  - id: bus_a
    sda: GPIO08
    scl: GPIO18
    scan: true

interval:
  - interval: 30s
    then:
      - script.execute: request_draw

touchscreen:
  - platform: gt911
    id: gt911_touchscreen
    display: box_display
    i2c_id: bus_a
    address: 0x5D
    interrupt_pin:
      number: GPIO3
      ignore_strapping_warning: true

binary_sensor:
  - platform: touchscreen
    page_id: home_page
    id: touch_test_fullscreen
    x_min: 0
    x_max: 320
    y_min: 0
    y_max: 240
    on_click:
      then:
        - display.page.show: climate_page
        - script.execute: request_draw

  - platform: touchscreen
    page_id: climate_page
    id: climate_back_fullscreen
    x_min: 0
    x_max: 320
    y_min: 0
    y_max: 240
    on_click:
      then:
        - display.page.show: home_page
        - script.execute: request_draw

sensor:
  - platform: homeassistant
    id: avg_indoor_temp
    entity_id: sensor.average_indoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.outdoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

display:
  - platform: ili9xxx
    model: S3BOX
    id: box_display
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    invert_colors: false
    update_interval: never
    pages:
      - id: home_page
        lambda: |-
          it.fill(Color(255,255,255));
          it.print(20, 20, id(font_title), Color(0,0,0), "HOME");

      - id: climate_page
        lambda: |-
          it.fill(Color(255,255,255));
          it.print(20, 20, id(font_title), Color(0,0,0), "CLIMATE");

font:
  - file:
      type: gfonts
      family: Figtree
      weight: 600
    id: font_title
    size: 18

script:
  - id: request_draw
    mode: restart
    then:
      - component.update: box_display
