# Box-3 Utilities Display (ESPHome Package)
# Version: 0.1.6
#
# PURE PACKAGE FILE (safe for `packages:` inclusion)
# Fixes:
# - Indoor/Outdoor sensor entity_ids matched to the original working config
# - HVAC action read from climate attribute (original behavior)
# - Layout tightened so Gas/Water are visible on 320x240
# - Redraw on sensor changes + safety refresh

substitutions:
  idle_color: 0xA7D8FF
  thermostat_entity: climate.ecobee_thermostat

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

interval:
  - interval: 30s
    then:
      - script.execute: request_draw

sensor:
  - platform: homeassistant
    id: avg_indoor_temp
    entity_id: sensor.average_indoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.outdoor_temperature
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_power_w
    entity_id: sensor.house_electric_meter_power_minute_average
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_energy_today
    entity_id: sensor.house_electric_meter_energy_today
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: homeassistant
    id: electric_energy_month
    entity_id: sensor.house_electric_meter_energy_this_month
    internal: true
    on_value:
      - script.execute: request_draw

  # Gas / Water placeholders (for now)
  - platform: template
    id: gas_month_ccf
    lambda: |-
      static float v = 12.3;
      v += 0.01;
      return v;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

  - platform: template
    id: water_month_gal
    lambda: |-
      static float v = 820;
      v += 1;
      return v;
    update_interval: 10s
    internal: true
    on_value:
      - script.execute: request_draw

text_sensor:
  - platform: homeassistant
    id: hvac_action
    entity_id: ${thermostat_entity}
    attribute: hvac_action
    internal: true
    on_value:
      - script.execute: request_draw

font:
  - file:
      type: gfonts
      family: Figtree
      weight: 600
    id: font_title
    size: 24

  - file:
      type: gfonts
      family: Figtree
      weight: 500
    id: font_label
    size: 18

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_value
    size: 26

display:
  - platform: ili9xxx
    model: S3BOX
    id: box_display
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    invert_colors: false
    update_interval: never
    lambda: |-
      const Color paper = Color(0xF3, 0xF1, 0xE7);
      const Color ink   = Color(0x11, 0x11, 0x11);
      const Color div   = Color(0xC9, 0xC6, 0xBB);

      it.fill(paper);

      // --- TOP STRIP (HVAC) ---
      it.print(10, 6, id(font_label), ink, "Indoor");
      if (!isnan(id(avg_indoor_temp).state)) {
        it.printf(10, 26, id(font_value), ink, "%.1f°", id(avg_indoor_temp).state);
      } else {
        it.print(10, 26, id(font_value), ink, "--");
      }

      it.print(120, 6, id(font_label), ink, "Outdoor");
      if (!isnan(id(outdoor_temp).state)) {
        it.printf(120, 26, id(font_value), ink, "%.1f°", id(outdoor_temp).state);
      } else {
        it.print(120, 26, id(font_value), ink, "--");
      }

      it.print(240, 6, id(font_label), ink, "HVAC");
      it.print(240, 26, id(font_label), ink, id(hvac_action).state.c_str());

      it.line(10, 58, 310, 58, div);

      // --- UTILITIES ---
      it.print(10, 64, id(font_title), ink, "UTILITIES");

      // Electric (tighter vertical spacing)
      it.print(10, 94, id(font_label), ink, "Electric");
      if (!isnan(id(electric_power_w).state)) {
        it.printf(10, 114, id(font_label), ink, "Now: %.0f W", id(electric_power_w).state);
      } else {
        it.print(10, 114, id(font_label), ink, "Now: -- W");
      }
      if (!isnan(id(electric_energy_today).state)) {
        it.printf(10, 132, id(font_label), ink, "Today: %.2f kWh", id(electric_energy_today).state);
      } else {
        it.print(10, 132, id(font_label), ink, "Today: -- kWh");
      }
      if (!isnan(id(electric_energy_month).state)) {
        it.printf(10, 150, id(font_label), ink, "Month: %.1f kWh", id(electric_energy_month).state);
      } else {
        it.print(10, 150, id(font_label), ink, "Month: -- kWh");
      }

      it.line(10, 168, 310, 168, div);

      // Gas / Water (now visible)
      it.print(10, 180, id(font_label), ink, "Gas Month");
      it.printf(170, 180, id(font_label), ink, "%.1f CCF", id(gas_month_ccf).state);

      it.print(10, 204, id(font_label), ink, "Water Month");
      it.printf(170, 204, id(font_label), ink, "%.0f gal", id(water_month_gal).state);

script:
  - id: request_draw
    mode: restart
    then:
      - component.update: box_display
