substitutions:
  name: box3-utilities-display
  friendly_name: Box-3 Utilities Display

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: screen_backlight
          brightness: 100%
      - script.execute: request_draw

esp32:
  board: esp32s3box
  framework:
    type: arduino

packages:
  - github://mrfixitpa/ESP32-S3-Utilities-Display/box-3-utilities.yaml@main
  
logger:

ota:
  - platform: esphome

api:
  encryption:
    key: enter in your encryption key here

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: xx.xx.xx.xx (un-comment if using a dedicated ip and add your ip)

# Backlight (HA toggle + brightness control)
output:
  - platform: ledc
    pin: GPIO47
    id: backlight_pwm

light:
  - platform: monochromatic
    id: screen_backlight
    name: "${friendly_name} Screen Backlight"
    output: backlight_pwm
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# Touch (tap anywhere = refresh screen for now)
i2c:
  scl: GPIO18
  sda: GPIO8

touchscreen:
  - platform: gt911
    id: box_touch
    interrupt_pin: GPIO3
    on_touch:
      then:
        - script.execute: request_draw
